server:
  port: 8081
spring:
  profiles:
    active: dev
    include: swagger
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/db_ex_stuff
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  mail:
    host: localhost
    port: 25
    username: cz.colin1@gmail.com
    password: Colin@123
  application:
    name: ExStuff
ExStuff:
  http:
    version: V_1_1
  cors:
    allowed-origins: '*'
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: '*'
    exposed-headers: null
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  swagger:
    default-include-pattern: /api/.*
    title: ExStuff API
    description: ExStuff API documentation
    version: 0.0.1
    terms-of-service-url: null
    contact-name: null
    contact-url: null
    contact-email: null
    license: null
    license-url: null
  logging:
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512